import fs from 'node:fs';
import { chromium } from 'playwright-core';
const candidates=[process.env.CHROME_PATH,'/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'].filter(Boolean);
const executablePath=candidates.find(p=>fs.existsSync(p));
if(!executablePath)throw new Error('No Chrome/Chromium executable found on runner');
const browser=await chromium.launch({headless:true,executablePath,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ko-KR'});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto('http://127.0.0.1:4173/player/',{waitUntil:'networkidle'});
const visible=async sel=>{if(!(await page.locator(sel).isVisible()))throw new Error(`${sel} not visible`)};
await page.locator('[data-scene-mode="simple"]').click();await visible('[data-scene-content="simple"]');await visible('[data-inspector-mode="simple"]');
await page.locator('[data-view="mixer"]').first().click();await visible('[data-panel="mixer"]');
await page.locator('[data-view="timer"]').first().click();await visible('[data-panel="timer"]');
await page.locator('[data-view="settings"]').first().click();await visible('[data-panel="settings"]');
await page.locator('[data-view="scene"]').first().click();await page.locator('[data-scene-mode="journey"]').click();await visible('[data-scene-content="journey"]');
await page.locator('[data-duration="600"]').click();if(!(await page.locator('#durationOutput').textContent())?.includes('10h'))throw new Error('10h shortcut failed');
await page.locator('#durationDirect').fill('10:15');await page.waitForTimeout(20);
const beforeApply=await page.evaluate(()=>({input:document.querySelector('#durationDirect')?.value,slider:document.querySelector('#durationSlider')?.value,step:document.querySelector('#durationSlider')?.step,output:document.querySelector('#durationOutput')?.textContent,controls:!!window.LullabyControls}));
await page.locator('#durationDirectApply').click();await page.waitForTimeout(50);
const directState=await page.evaluate(()=>({output:document.querySelector('#durationOutput')?.textContent,input:document.querySelector('#durationDirect')?.value,slider:document.querySelector('#durationSlider')?.value,step:document.querySelector('#durationSlider')?.step,controls:!!window.LullabyControls,applyDirect:typeof window.LullabyControls?.applyDirect,setDuration:typeof window.setDuration}));
if(!directState.output?.includes('10h 15m'))throw new Error(`minute-precise HH:MM duration failed: before=${JSON.stringify(beforeApply)} after=${JSON.stringify(directState)}; page errors=${errors.join(' | ')}`);if(directState.input!=='10:15')throw new Error(`HH:MM input was rounded: before=${JSON.stringify(beforeApply)} after=${JSON.stringify(directState)}`);
await page.locator('[data-scene-mode="simple"]').click();await page.locator('[data-fx="warmth"]').evaluate(el=>{el.value='72';el.dispatchEvent(new Event('input',{bubbles:true}))});if((await page.locator('[data-fx-output="warmth"]').textContent())!=='72%')throw new Error('Simple Scene FX control failed');
await page.locator('.language-toggle').click();if((await page.locator('[data-scene-mode="simple"]').textContent())?.trim()!=='Simple Scenes')throw new Error('language toggle failed');
if(errors.length)throw new Error(`browser errors: ${errors.join(' | ')}`);
await browser.close();
console.log('web interaction smoke test passed');
