const languageToggle=document.getElementById('languageToggle');
let language=localStorage.getItem('lullaby-language')||((navigator.language||'').toLowerCase().startsWith('ko')?'ko':'en');
function applyLanguage(){document.documentElement.lang=language;languageToggle.textContent=language==='ko'?'EN':'KO';languageToggle.setAttribute('aria-label',language==='ko'?'Switch to English':'한국어로 전환')}
languageToggle?.addEventListener('click',()=>{language=language==='ko'?'en':'ko';localStorage.setItem('lullaby-language',language);applyLanguage()});applyLanguage();
document.getElementById('year').textContent=new Date().getFullYear();
let deferredInstall;const installButton=document.getElementById('installPwa');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;installButton.hidden=false});installButton?.addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;installButton.hidden=true});window.addEventListener('appinstalled',()=>{installButton.hidden=true});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));

const AudioCtx=window.AudioContext||window.webkitAudioContext;
let ctx,master,aircraft=null,sceneTimer=null,sceneStartedAt=0,pausedAt=0,scenePlaying=false,durationMinutes=480;
const macro={engine:.55,activity:.22,turbulence:.12,night:.68};
const sourceDefs={rain:'/audio/rain.ogg',fire:'/audio/fire.ogg',ocean:'/audio/ocean.ogg',train:'/audio/train.ogg'};
const mixer={};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function setStatus(t){$('#playerStatus').textContent=t}
async function ensureContext(){if(!ctx){ctx=new AudioCtx();master=ctx.createGain();master.gain.value=.7;master.connect(ctx.destination)}if(ctx.state==='suspended')await ctx.resume()}
function makeMediaNode(url){const el=new Audio(url);el.loop=true;el.preload='auto';const src=ctx.createMediaElementSource(el),filter=ctx.createBiquadFilter(),gain=ctx.createGain();filter.type='lowpass';filter.frequency.value=18000;src.connect(filter).connect(gain).connect(master);return{el,src,filter,gain}}
async function getAircraftUrl(){const parts=await Promise.all([0,1,2,3].map(i=>fetch(`/audio/aircraft.part0${i}`).then(r=>{if(!r.ok)throw new Error('aircraft asset');return r.text()})));const b64=parts.join('').replace(/\s/g,'');const bin=atob(b64);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return URL.createObjectURL(new Blob([bytes],{type:'audio/ogg'}))}
async function ensureAircraft(){await ensureContext();if(aircraft)return aircraft;setStatus('Passenger Aircraft Cabin 오디오를 준비하는 중…');const url=await getAircraftUrl();aircraft=makeMediaNode(url);aircraft.gain.gain.value=.55;return aircraft}

function phaseFor(ms,total){const m=ms/60000,t=total/60000;if(m<12)return['Taxi out',true];if(m<13.2)return['Takeoff',true];if(m<27)return['Climb',true];if(m<t-42)return['Cruise',false];if(m<t-15)return['Descent',true];if(m<t-7)return['Approach',true];if(m<t-6)return['Touchdown',true];if(m<t)return['Taxi in',true];return['Arrived',false]}
function fmt(ms,compact=false){ms=Math.max(0,ms);const sec=Math.floor(ms/1000),h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;if(compact&&h===0)return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function currentElapsed(){return scenePlaying?pausedAt+(performance.now()-sceneStartedAt):pausedAt}
function updateSceneAudio(ms){if(!aircraft)return;const total=durationMinutes*60000;const [phase]=phaseFor(ms,total);let phaseGain={"Taxi out":.58,Takeoff:.82,Climb:.72,Cruise:.6,Descent:.64,Approach:.7,Touchdown:.76,"Taxi in":.54,Arrived:0}[phase]??.6;const turbulence=Math.sin(ms/2200)*macro.turbulence*.05;const gain=Math.max(0,phaseGain*(.45+macro.engine*.7)+turbulence);aircraft.gain.gain.setTargetAtTime(gain,ctx.currentTime,.8);const cutoff=Math.max(1800,17000-(macro.night*8500)-((1-macro.engine)*2600));aircraft.filter.frequency.setTargetAtTime(cutoff,ctx.currentTime,1.2)}
function updateSceneUi(){const elapsed=currentElapsed(),total=durationMinutes*60000,remaining=Math.max(0,total-elapsed),[phase,belt]=phaseFor(elapsed,total);$('#phaseLabel').textContent=phase;$('#elapsedLabel').textContent=fmt(elapsed,true);$('#remainingLabel').textContent=fmt(remaining);$('#seatbeltLabel').textContent=belt?'ON':'OFF';$('#journeyProgress').style.width=`${Math.min(100,elapsed/total*100)}%`;$('#railNowPlaying').textContent=scenePlaying?'Passenger Aircraft Cabin':'Paused';let event='None';if(phase==='Cruise'&&elapsed>90*60000){const cycle=Math.floor(elapsed/(105*60000));const within=elapsed%(105*60000);if(within<70000&&macro.turbulence>.05)event='Light turbulence';else if(within>45*60000&&within<46*60000&&macro.activity>.05)event='Quiet cabin movement'}$('#eventLabel').textContent=event;updateSceneAudio(elapsed);if(elapsed>=total){stopScene(true)}}
async function startScene(){try{await ensureAircraft();if(!scenePlaying){sceneStartedAt=performance.now();scenePlaying=true;await aircraft.el.play();$('#scenePlay').textContent='Ⅱ 일시정지';setStatus('Passenger Aircraft Cabin 재생 중');sceneTimer=setInterval(updateSceneUi,1000);updateSceneUi()}else{pauseScene()}}catch(e){console.error(e);setStatus('오디오를 시작하지 못했습니다. 브라우저의 자동재생/오디오 권한을 확인해 주세요.') }}
function pauseScene(){if(!scenePlaying)return;pausedAt=currentElapsed();scenePlaying=false;aircraft?.el.pause();clearInterval(sceneTimer);$('#scenePlay').textContent='▶ 계속 재생';$('#railNowPlaying').textContent='Paused';setStatus('일시정지됨')}
function stopScene(arrived=false){scenePlaying=false;pausedAt=0;clearInterval(sceneTimer);if(aircraft){aircraft.el.pause();aircraft.el.currentTime=0;aircraft.gain.gain.value=.55}$('#scenePlay').textContent='▶ 장면 시작';$('#phaseLabel').textContent=arrived?'Arrived':'Ready';$('#elapsedLabel').textContent='00:00';$('#remainingLabel').textContent=fmt(durationMinutes*60000);$('#seatbeltLabel').textContent='—';$('#journeyProgress').style.width='0';$('#railNowPlaying').textContent='Stopped';$('#eventLabel').textContent='None';setStatus(arrived?'여정이 종료되었습니다.':'정지됨')}
$('#scenePlay')?.addEventListener('click',startScene);$('#sceneStop')?.addEventListener('click',()=>stopScene(false));
$('#masterVolume')?.addEventListener('input',e=>{if(master)master.gain.setTargetAtTime(+e.target.value/100,ctx.currentTime,.05)});
function setDuration(v){durationMinutes=+v;$('#durationSlider').value=v;$('#durationOutput').textContent=(v%60?`${Math.floor(v/60)}h ${v%60}m`:`${v/60}h`);$$('[data-duration]').forEach(b=>b.classList.toggle('active',+b.dataset.duration===+v));if(!scenePlaying&&pausedAt===0)$('#remainingLabel').textContent=fmt(durationMinutes*60000);updateSceneUi()}
$('#durationSlider')?.addEventListener('input',e=>setDuration(e.target.value));$$('[data-duration]').forEach(b=>b.addEventListener('click',()=>setDuration(b.dataset.duration)));
$$('[data-macro]').forEach(input=>input.addEventListener('input',e=>{const k=e.target.dataset.macro,v=+e.target.value/100;macro[k]=v;$$(`[data-output="${k}"]`).forEach(o=>o.textContent=`${Math.round(v*100)}%`);$$(`[data-macro="${k}"]`).forEach(other=>{if(other!==e.target)other.value=e.target.value});updateSceneAudio(currentElapsed())}));

async function toggleMixer(id){await ensureContext();if(!mixer[id])mixer[id]=makeMediaNode(sourceDefs[id]);const node=mixer[id],card=$(`.mixer-source[data-source="${id}"]`),btn=$(`[data-source-toggle="${id}"]`);if(node.el.paused){node.gain.gain.value=+($(`[data-source-volume="${id}"]`).value)/100;await node.el.play();card.classList.add('on');btn.textContent='On'}else{node.el.pause();card.classList.remove('on');btn.textContent='Off'}}
$$('[data-source-toggle]').forEach(b=>b.addEventListener('click',()=>toggleMixer(b.dataset.sourceToggle).catch(e=>{console.error(e);setStatus('Mixer 오디오를 시작하지 못했습니다.')})));$$('[data-source-volume]').forEach(r=>r.addEventListener('input',e=>{const n=mixer[e.target.dataset.sourceVolume];if(n&&ctx)n.gain.gain.setTargetAtTime(+e.target.value/100,ctx.currentTime,.05)}));
function switchView(view){$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===view))}$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
setDuration(480);
