(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={ctx:null,master:null,eqLow:null,eqHigh:null,comp:null,masterGain:.7,catalog:[],nodes:new Map(),events:new Map(),sceneMode:'journey',journey:{playing:false,elapsed:0,startAt:0,duration:480,timer:null,node:null,vent:null,brown:null},simple:{active:null},sleepTimer:null};
const lang=()=>window.LullabyI18n?.language||'ko';
const tr=(ko,en)=>lang()==='ko'?ko:en;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function fmt(ms){ms=Math.max(0,ms);const s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
function setStatus(text){const el=$('#playerStatus');if(el)el.textContent=text}
async function audio(){if(!state.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)throw new Error('Web Audio unavailable');const c=state.ctx=new C();state.eqLow=c.createBiquadFilter();state.eqLow.type='lowshelf';state.eqLow.frequency.value=240;state.eqHigh=c.createBiquadFilter();state.eqHigh.type='lowpass';state.eqHigh.frequency.value=18000;state.comp=c.createDynamicsCompressor();state.comp.threshold.value=-14;state.comp.knee.value=18;state.comp.ratio.value=2;state.comp.attack.value=.02;state.comp.release.value=.35;state.master=c.createGain();state.master.gain.value=state.masterGain;state.eqLow.connect(state.eqHigh).connect(state.comp).connect(state.master).connect(c.destination)}if(state.ctx.state==='suspended')await state.ctx.resume();return state.ctx}
function mediaNode(url,{loop=true,target='master'}={}){const el=new Audio(url);el.loop=loop;el.preload='auto';const src=state.ctx.createMediaElementSource(el),gain=state.ctx.createGain(),filter=state.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=20000;src.connect(filter).connect(gain).connect(target==='master'?state.eqLow:target);return{el,src,gain,filter}}
async function aircraftUrl(){const parts=await Promise.all([0,1,2,3].map(i=>fetch(`/audio/aircraft.part0${i}`).then(r=>{if(!r.ok)throw new Error('aircraft payload');return r.text()})));const bin=atob(parts.join('').replace(/\s/g,'')),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return URL.createObjectURL(new Blob([bytes],{type:'audio/ogg'}))}
async function loadCatalog(){const r=await fetch('/mixer-sources.json',{cache:'no-cache'});if(!r.ok)throw new Error('catalog');state.catalog=(await r.json()).sources||[];renderMixer();renderSimpleScenes();}
function source(id){return state.catalog.find(x=>x.id===id)}
function sourceState(id){const n=state.nodes.get(id);return{on:!!n&&!n.el.paused,vol:n?Math.round(n.gain.gain.value*100):(source(id)?.defaultVolume||30)}}
async function toggleSource(id){const def=source(id);if(!def)return;await audio();let n=state.nodes.get(id);if(!n){n=mediaNode(def.url,{loop:def.kind!=='event'});n.gain.gain.value=(def.defaultVolume||30)/100;state.nodes.set(id,n)}if(n.el.paused){n.el.currentTime=0;await n.el.play()}else n.el.pause();renderMixer();renderInspector();updateNowPlaying()}
function setSourceVolume(id,v){const n=state.nodes.get(id);if(n&&state.ctx)n.gain.gain.setTargetAtTime(v,state.ctx.currentTime,.04)}
function stopMixer(){state.nodes.forEach(n=>{n.el.pause();n.el.currentTime=0});renderMixer();renderInspector();updateNowPlaying()}
function renderMixer(){const root=$('#mixerGrid');if(!root)return;const filter=$('.mixer-filters .active')?.dataset.filter||'all';const list=filter==='all'?state.catalog:state.catalog.filter(x=>x.category===filter);root.innerHTML=list.map(d=>{const st=sourceState(d.id);return `<article class="mixer-source ${st.on?'on':''}"><div><strong>${d.name}</strong><span>${d.category} · ${d.kind==='event'?tr('이벤트','event'):tr('연속','continuous')}</span></div><button type="button" data-src-toggle="${d.id}">${st.on?tr('켬','On'):tr('끔','Off')}</button><input data-src-vol="${d.id}" type="range" min="0" max="100" value="${st.vol}"></article>`}).join('')}
const simpleScenes=[['Rainy Cafe',{rain:.5,cafe:.35}],['Forest Night',{forest:.42,crickets:.22,wind:.12}],['Cozy Fireplace',{fire:.5,rain:.24}],['Train Journey',{train:.5,city:.18}],['Quiet Night',{brown_noise:.34,crickets:.18,wind:.1}],['Ocean Waves',{ocean:.5,white_noise:.1}],['Rainy Night',{rain:.5,brown_noise:.18}],['Cafe Focus',{cafe:.35,pink_noise:.18}]];
function renderSimpleScenes(){const root=$('#builtInPresets');if(root)root.innerHTML=simpleScenes.map(([name,mix],i)=>`<button class="preset-card" type="button" data-simple="${i}"><strong>${name}</strong><span>${Object.keys(mix).length} ${tr('개 소스','sources')}</span></button>`).join('');const user=$('#userPresets');if(user){let list=[];try{list=JSON.parse(localStorage.getItem('lullaby-user-presets')||'[]')}catch{}user.innerHTML=list.length?list.map(p=>`<button class="preset-card" type="button" data-user-simple="${p.id}"><strong>${p.name}</strong><span>${Object.keys(p.mix||{}).length} ${tr('개 소스','sources')}</span></button>`).join(''):`<p class="muted-copy">${tr('저장한 심플 씬이 없습니다.','No saved Simple Scenes.')}</p>`}}
async function applySimple(mix,name){stopJourney(false);stopMixer();await audio();for(const [id,v] of Object.entries(mix)){const def=source(id);if(!def)continue;const n=mediaNode(def.url,{loop:def.kind!=='event'});n.gain.gain.value=v;state.nodes.set(id,n);await n.el.play()}state.simple.active=name;state.sceneMode='simple';renderMixer();renderInspector();updateNowPlaying();setStatus(`${name} ${tr('심플 씬 재생 중','is playing')}`)}
function phase(ms,total){const m=ms/60000,t=total/60000;if(m<12)return['Taxi out',true];if(m<13.2)return['Takeoff',true];if(m<27)return['Climb',true];if(m<t-42)return['Cruise',false];if(m<t-15)return['Descent',true];if(m<t-7)return['Approach',true];if(m<t)return['Taxi in',true];return['Arrived',false]}
function journeyElapsed(){return state.journey.playing?state.journey.elapsed+(performance.now()-state.journey.startAt):state.journey.elapsed}
async function ensureJourney(){await audio();if(!state.journey.node){state.journey.node=mediaNode(await aircraftUrl());state.journey.node.gain.gain.value=.52;const vent=source('ventilation'),brown=source('brown_noise');if(vent){state.journey.vent=mediaNode(vent.url);state.journey.vent.gain.gain.value=.13}if(brown){state.journey.brown=mediaNode(brown.url);state.journey.brown.gain.gain.value=.08}}}
async function playJourney(){await ensureJourney();if(state.journey.playing){pauseJourney();return}stopMixer();state.journey.startAt=performance.now();state.journey.playing=true;await Promise.all([state.journey.node,state.journey.vent,state.journey.brown].filter(Boolean).map(n=>n.el.play()));$('#scenePlay').textContent=tr('Ⅱ 일시정지','Ⅱ Pause');state.journey.timer=setInterval(updateJourney,500);updateJourney();updateNowPlaying()}
function pauseJourney(){if(!state.journey.playing)return;state.journey.elapsed=journeyElapsed();state.journey.playing=false;clearInterval(state.journey.timer);[state.journey.node,state.journey.vent,state.journey.brown].filter(Boolean).forEach(n=>n.el.pause());$('#scenePlay').textContent=tr('▶ 계속 재생','▶ Resume');updateNowPlaying()}
function stopJourney(reset=true){clearInterval(state.journey.timer);state.journey.playing=false;if(reset)state.journey.elapsed=0;[state.journey.node,state.journey.vent,state.journey.brown].filter(Boolean).forEach(n=>{n.el.pause();if(reset)n.el.currentTime=0});if($('#scenePlay'))$('#scenePlay').textContent=tr('▶ 장면 시작','▶ Start journey');updateJourney();updateNowPlaying()}
function updateJourney(){const e=journeyElapsed(),total=state.journey.duration*60000,[p,belt]=phase(e,total);if($('#phaseLabel'))$('#phaseLabel').textContent=p;if($('#elapsedLabel'))$('#elapsedLabel').textContent=fmt(e);if($('#remainingLabel'))$('#remainingLabel').textContent=fmt(total-e);if($('#seatbeltLabel'))$('#seatbeltLabel').textContent=belt?'ON':'OFF';if($('#journeyProgress'))$('#journeyProgress').style.width=`${clamp(e/total*100,0,100)}%`;const engine=+($('[data-macro="engine"]')?.value||55)/100,night=+($('[data-macro="night"]')?.value||68)/100,turb=+($('[data-macro="turbulence"]')?.value||12)/100;if(state.ctx&&state.journey.node){const g={"Taxi out":.5,Takeoff:.78,Climb:.67,Cruise:.54,Descent:.6,Approach:.66,"Taxi in":.48,Arrived:0}[p]??.54;state.journey.node.gain.gain.setTargetAtTime(g*(.5+engine*.65),state.ctx.currentTime,.5);state.journey.node.filter.frequency.setTargetAtTime(17000-night*9000,state.ctx.currentTime,.8);if(state.journey.vent)state.journey.vent.gain.gain.setTargetAtTime(.08+.14*(1-night),state.ctx.currentTime,.8);if(state.journey.brown)state.journey.brown.gain.gain.setTargetAtTime(.04+.08*engine+.025*turb,state.ctx.currentTime,.8)}if(e>=total)stopJourney(true)}
function setDuration(min){state.journey.duration=clamp(Math.round(min),240,720);if($('#durationSlider'))$('#durationSlider').value=state.journey.duration;if($('#durationOutput'))$('#durationOutput').textContent=`${Math.floor(state.journey.duration/60)}h${state.journey.duration%60?` ${state.journey.duration%60}m`:''}`;$$('[data-duration]').forEach(b=>b.classList.toggle('active',+b.dataset.duration===state.journey.duration));syncDirect();updateJourney()}
function syncDirect(){const i=$('#durationDirect');if(i){const h=Math.floor(state.journey.duration/60),m=state.journey.duration%60;i.value=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}}
function applyDirect(){const i=$('#durationDirect'),err=$('#durationDirectError');if(!i)return;const m=/^(\d{1,2}):([0-5]\d)$/.exec(i.value.trim());const min=m?(+m[1]*60 + +m[2]):NaN;if(!Number.isFinite(min)||min<240||min>720){if(err){err.hidden=false;err.textContent=tr('04:00~12:00 사이로 입력해 주세요.','Enter a time from 04:00 to 12:00.')}return}if(err)err.hidden=true;setDuration(min)}
function makeDirectInput(){const c=$('.duration-control');if(!c||$('#durationDirect'))return;c.insertAdjacentHTML('beforeend',`<div class="duration-direct"><div class="duration-direct-copy"><strong>${tr('직접 입력','Direct input')}</strong><span>HH:MM · 04:00–12:00</span></div><div class="duration-direct-entry"><input id="durationDirect" inputmode="numeric" value="08:00" maxlength="5"><button id="durationDirectApply" type="button">${tr('적용','Apply')}</button></div><p id="durationDirectError" class="duration-direct-error" hidden></p></div>`)}
function setSceneMode(mode){state.sceneMode=mode==='simple'?'simple':'journey';$$('[data-scene-mode]').forEach(b=>b.classList.toggle('active',b.dataset.sceneMode===state.sceneMode));$$('[data-scene-content]').forEach(p=>p.classList.toggle('active',p.dataset.sceneContent===state.sceneMode));renderInspector()}
function renderInspector(){const aside=$('.desktop-inspector');if(!aside)return;if(state.sceneMode==='journey'){aside.innerHTML=`<div class="inspector-section"><p class="eyebrow">${tr('잠의 여정','Sleep Journey')}</p><h3>Passenger Aircraft Cabin</h3><p class="muted-copy">${tr('시간과 상태에 따라 장면이 변화합니다.','The scene evolves with time and state.')}</p></div><div class="inspector-section desktop-macros"><label>${tr('엔진 존재감','Engine presence')} <output data-output="engine">55%</output><input data-macro="engine" type="range" min="0" max="100" value="55"></label><label>${tr('기내 활동감','Cabin activity')} <output data-output="activity">22%</output><input data-macro="activity" type="range" min="0" max="100" value="22"></label><label>${tr('난기류','Turbulence')} <output data-output="turbulence">12%</output><input data-macro="turbulence" type="range" min="0" max="100" value="12"></label><label>${tr('밤의 깊이','Night depth')} <output data-output="night">68%</output><input data-macro="night" type="range" min="0" max="100" value="68"></label></div>`;return}
const active=[...state.nodes.entries()].filter(([,n])=>!n.el.paused);aside.innerHTML=`<div class="inspector-section"><p class="eyebrow">Simple Scene</p><h3>${state.simple.active||tr('믹스 조정','Mix controls')}</h3><p class="muted-copy">${tr('오른쪽에서 현재 심플 씬을 바로 다듬을 수 있습니다.','Tweak the current Simple Scene right here.')}</p></div><div class="inspector-section"><small>${tr('활성 소스','ACTIVE SOURCES')}</small><div class="mini-mixer">${active.length?active.map(([id,n])=>`<label>${source(id)?.name||id}<input data-mini-vol="${id}" type="range" min="0" max="100" value="${Math.round(n.gain.gain.value*100)}"></label>`).join(''):`<p class="muted-copy">${tr('재생 중인 소스가 없습니다.','No active sources.')}</p>`}</div></div><div class="inspector-section plugin-rack"><small>DSP RACK</small><label>${tr('따뜻함','Warmth EQ')} <output id="warmthOut">0 dB</output><input id="warmthPlugin" type="range" min="-6" max="6" value="0" step="1"></label><label>${tr('밤 공기','Night Air')} <output id="airOut">18 kHz</output><input id="airPlugin" type="range" min="3500" max="20000" value="18000" step="500"></label><label>${tr('부드러운 압축','Soft Compression')} <output id="compOut">2.0:1</output><input id="compPlugin" type="range" min="1" max="4" value="2" step="0.25"></label><label>Master <output id="masterOut">${Math.round(state.masterGain*100)}%</output><input id="masterPlugin" type="range" min="0" max="100" value="${Math.round(state.masterGain*100)}"></label></div>`}
function updateNowPlaying(){const n=[...state.nodes.values()].filter(x=>!x.el.paused).length+(state.journey.playing?1:0);if($('#railNowPlaying'))$('#railNowPlaying').textContent=n?`${n} active`:'Stopped'}
function switchView(v){$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===v));if($('#mobileTitle'))$('#mobileTitle').textContent={scene:'Scenes',mixer:'Mixer',timer:tr('취침 타이머','Sleep Timer'),settings:'Settings'}[v]||v}
function bind(){document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.sceneMode){setSceneMode(b.dataset.sceneMode);return}if(b.dataset.view){switchView(b.dataset.view);return}if(b.id==='scenePlay'){await playJourney();return}if(b.id==='sceneStop'){stopJourney(true);return}if(b.dataset.duration){setDuration(+b.dataset.duration);return}if(b.id==='durationDirectApply'){applyDirect();return}if(b.dataset.srcToggle){await toggleSource(b.dataset.srcToggle);return}if(b.id==='stopAllMixer'){stopMixer();return}if(b.dataset.simple!==undefined){const [name,mix]=simpleScenes[+b.dataset.simple];await applySimple(mix,name);setSceneMode('simple');return}if(b.dataset.userSimple){let list=[];try{list=JSON.parse(localStorage.getItem('lullaby-user-presets')||'[]')}catch{}const p=list.find(x=>x.id===b.dataset.userSimple);if(p){await applySimple(p.mix,p.name);setSceneMode('simple')}return}if(b.id==='savePreset'){const name=prompt(tr('심플 씬 이름','Simple Scene name'));if(!name)return;const mix={};state.nodes.forEach((n,id)=>{if(!n.el.paused)mix[id]=n.gain.gain.value});let list=[];try{list=JSON.parse(localStorage.getItem('lullaby-user-presets')||'[]')}catch{}list.push({id:`u${Date.now()}`,name,mix});localStorage.setItem('lullaby-user-presets',JSON.stringify(list));renderSimpleScenes();return}if(b.dataset.timerMinutes){startTimer(+b.dataset.timerMinutes);return}if(b.id==='startCustomTimer'){const m=+$('#customTimer')?.value;if(m>0)startTimer(m);return}if(b.id==='cancelTimer'){clearTimer();return}if(b.id==='clearCache'&&'caches'in window){for(const k of await caches.keys())await caches.delete(k);setStatus(tr('캐시를 비웠습니다.','Cache cleared.'));return}});document.addEventListener('input',e=>{const t=e.target;if(t.id==='durationSlider')setDuration(+t.value);if(t.dataset.srcVol)setSourceVolume(t.dataset.srcVol,+t.value/100);if(t.dataset.miniVol)setSourceVolume(t.dataset.miniVol,+t.value/100);if(t.dataset.macro){const out=$(`[data-output="${t.dataset.macro}"]`);if(out)out.textContent=`${t.value}%`;updateJourney()}if(t.id==='warmthPlugin'&&state.eqLow){state.eqLow.gain.value=+t.value;$('#warmthOut').textContent=`${t.value} dB`}if(t.id==='airPlugin'&&state.eqHigh){state.eqHigh.frequency.value=+t.value;$('#airOut').textContent=`${Math.round(t.value/1000)} kHz`}if(t.id==='compPlugin'&&state.comp){state.comp.ratio.value=+t.value;$('#compOut').textContent=`${t.value}:1`}if(t.id==='masterPlugin'){state.masterGain=+t.value/100;if(state.master)state.master.gain.value=state.masterGain;$('#masterOut').textContent=`${t.value}%`}});$('#durationDirect')?.addEventListener('keydown',e=>{if(e.key==='Enter')applyDirect()});$$('.mixer-filters').forEach(f=>f.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;f.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));renderMixer()}));}
function startTimer(m){clearTimer();const end=Date.now()+m*60000;state.sleepTimer=setInterval(()=>{const rem=end-Date.now();if($('#timerRemaining'))$('#timerRemaining').textContent=fmt(rem);if(rem<=0){clearTimer();stopJourney(true);stopMixer()}},500);if($('#cancelTimer'))$('#cancelTimer').hidden=false;switchView('timer')}
function clearTimer(){if(state.sleepTimer)clearInterval(state.sleepTimer);state.sleepTimer=null;if($('#timerRemaining'))$('#timerRemaining').textContent=tr('꺼짐','Off');if($('#cancelTimer'))$('#cancelTimer').hidden=true}
function styleFilters(){const f=$('#mixerFilters');if(f&&!f.children.length)f.innerHTML=[['all',tr('전체','All')],['nature',tr('자연','Nature')],['indoor',tr('실내','Indoor')],['travel',tr('이동','Travel')],['other',tr('기타','Other')]].map(([id,n],i)=>`<button type="button" data-filter="${id}" class="${i===0?'active':''}">${n}</button>`).join('')}
async function init(){try{makeDirectInput();styleFilters();bind();setDuration(480);setSceneMode(new URL(location.href).searchParams.get('scene')==='simple'?'simple':'journey');await loadCatalog();renderInspector();window.addEventListener('lullaby-language-changed',()=>{styleFilters();renderMixer();renderSimpleScenes();renderInspector();syncDirect()});setStatus(tr('재생할 준비가 되었습니다.','Ready to play.'))}catch(err){console.error(err);setStatus(tr('플레이어 초기화 오류가 발생했습니다.','Player initialization failed.'));}}
init();
})();
